DROP TABLE IF EXISTS EVENTS CASCADE;

CREATE TABLE IF NOT EXISTS EVENTS (
    ID      INTEGER AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INTEGER NOT NULL,
    STATUS  VARCHAR(25) NOT NULL,
    EVENT   CLOB NOT NULL,
    CREATED TIMESTAMP NOT NULL
);


